name: myenv
channels:
  - defaults
  - conda-forge
dependencies:

  - python=3.12.4
  - voila
  - jupyterlab
  - pandas
  - matplotlib
  - bqplot
  - ipympl
  - ipyvolume
  - scipy
  - pip
  - pip:
    - pyswip
    - swiplserver
    - swipl
