name: myenv
channels:
  - defaults
dependencies:
  - python=3.12.4
  - voila
  - jupyterlab
  - pandas
  - matplotlib
  - bqplot
  - ipympl
  - ipyvolume
  - scipy
  - swipl
  - pip
  - pip:
    - pyswip
    - swiplserver
