# Usa la imagen base de SWI-Prolog
FROM swipl:latest

# Copia los archivos del repositorio al contenedor
COPY . /app

# Establece el directorio de trabajo
WORKDIR /app

# Exponemos el puerto en el que Voila correrá
EXPOSE 8888
